import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import Layout from '@/components/Layout'
import './globals.scss'

export const roboto = Roboto({ subsets: ['cyrillic'], weight: ['400', '500'] })

export const metadata: Metadata = {
  title: 'Lumincoin',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        {/* for loader implementaion */}
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
